parameters:
#    serie_admin.example.class: Serie\AdminBundle\Example

services:
#    serie_admin.example:
#        class: %serie_admin.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
