<?php

namespace Serie\AdminBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * SettingsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SettingsRepository extends EntityRepository
{
	public function getAllSettingsQuery()
	{
		return $this->_em
                    ->createQueryBuilder('s')
                    ->select('s')
                    ->from('SerieAdminBundle:Settings', 's')
                    ->getQuery();
	}
}
