<?php

namespace Serie\SerieBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ActorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ActorRepository extends EntityRepository
{

	public function getAllActorsQuery()
	{
		return $this->_em
                    ->createQueryBuilder('a')
                    ->select('a')
                    ->from('SerieSerieBundle:Actor', 'a')
                    ->getQuery();
	}
}
